name: push sutter page to <app_name> static webapp
run-name: ${{ github.ref_name }} ${{ github.actor }}

on:
  workflow_dispatch:
  check_run:
    types:
      - completed
  push:
    branches:
      - master
    paths:
      - '<app_name>/**'
      - .github/workflows/<file_name>.yaml

  pull_request:
    types: [opened]
    branches:
      - master
    paths:
      - '<app_name>/**'
      - .github/workflows/<file_name>.yaml

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    uses: hmcts/azure-shutter-pages/.github/workflows/deploy-shutter-pages.yaml@master
    with:
      WEBAPP_TOKEN: ${{ secrets.<app_name_secret>_<env> }}
      appname: "<app_name>" # App source code path relative to repository root. Enter "default" for default pages.
