
name: push default page
run-name: ${{ github.ref_name }} ${{ github.actor }}

on:
  push:
    branches:
      - master
    paths:
      - 'default/**'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths:
      - 'default/**'

jobs:
  build_and_deploy_job:
    strategy:
      matrix:
        include: # add application
          - name: "toffee"
          - name: "plum"
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets[matrix.name] }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "default" # App source code path relative to repository root
