name: Default shutter pages deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Run every hour
  
  pull_request:
    types: [opened]
    branches:
      - master
    paths:
      - 'default/**'
      - .github/workflows/default.yaml

permissions:
  id-token: write
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    outputs:
      webapp_token: ${{ steps.export_var.outputs.webapp_token }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: AZ CLI login
      uses: azure/login@v2
      with:
        client-id: 633b591d-916a-4a38-8132-dd34e0b8dd4e # custom-domain-revalidator
        tenant-id: 531ff96d-0ae9-462a-8d2d-bec7c0b42082 # HMCTS.NET
        allow-no-subscriptions: true

    - name: find-empty-static-app.sh
      id: export_var
      run: |
        chmod +x ./scripts/find-empty-static-app.sh
        source ./scripts/find-empty-static-app.sh
        echo "webapp_token=$WEBAPP_TOKEN"
        echo "webapp_token=$WEBAPP_TOKEN" >> "$GITHUB_OUTPUT"  # Store for next job securely

  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    uses: hmcts/azure-shutter-pages/.github/workflows/deploy-shutter-pages.yaml@master
    with:
      shutter_page_folder: "default"
    secrets:
      WEBAPP_TOKEN: ${{ needs.run-script.outputs.webapp_token }} # Use the output from the previous job
    needs: run-script