name: push shutter pages to webapp
on:
  workflow_call:
    secrets:
      WEBAPP_TOKEN:
        required: true
        description: Static webapp deployment token
    inputs:
      shutter_page_folder:
        required: true
        type: string 

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.WEBAPP_TOKEN}}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: ${{ inputs.appname }} # App source code path relative to repository root. Enter "default" for default pages.
