name: push shutter page to div-amend static webapp
run-name: ${{ github.ref_name }} ${{ github.actor }}

on:
  workflow_dispatch:
  check_run:
    types:
      - completed
  push:
    branches:
      - master
    paths:
      - 'default/**'
      - .github/workflows/div-amend.yaml

  pull_request:
    types: [opened]
    branches:
      - master
    paths:
      - 'default/**'
      - .github/workflows/div-amend.yaml

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: hmcts/azure-shutter-pages/.github/workflows/deploy-shutter-pages.yaml@master
    with:
      shutter_page_folder: "default" # App source code path relative to repository root. Enter "default" for default pages.
    secrets:
      WEBAPP_TOKEN: ${{ secrets.DIV_AMEND_PROD }}