name: push shutter page to jd-reply-jury-summons static webapp
run-name: ${{ github.ref_name }} ${{ github.actor }}

on:
  workflow_dispatch:
  check_run:
    types:
      - completed
  push:
    branches:
      - master
    paths:
      - 'juror-legacy/**'
      - .github/workflows/jd-reply-jury-summons.yaml

  pull_request:
    types: [opened]
    branches:
      - master
    paths:
      - 'juror-legacy/**'
      - .github/workflows/jd-reply-jury-summons.yaml

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: hmcts/azure-shutter-pages/.github/workflows/deploy-shutter-pages.yaml@master
    with:
      shutter_page_folder: "juror-legacy" # App source code path relative to repository root. Enter "default" for default pages.
    secrets:
      WEBAPP_TOKEN: ${{ secrets.JD_REPLY_JURY_SUMMONS_PROD }}
