name: Deploy OPAL page to opal-rm-frontend Sbox shutter app
run-name: ${{ github.ref_name }} ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'opal/**'
      - '.github/workflows/opal-rm-frontend-sbox.yaml'
  pull_request:
    types: [opened]
    branches:
      - master
    paths:
      - 'opal/**'
      - '.github/workflows/opal-rm-frontend-sbox.yaml'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: hmcts/azure-shutter-pages/.github/workflows/deploy-shutter-pages.yaml@master
    with:
      shutter_page_folder: opal
    secrets:
      WEBAPP_TOKEN: ${{ secrets.OPAL_RM_FRONTEND_SBOX }}
