name: push custom page
run-name: ${{ github.ref_name }} ${{ github.actor }}

on:
  push:
    branches:
      - master
    paths:
      - 'plum/**'
      - .github/workflows/plum.yaml

  pull_request:
    types: [opened]
    branches:
      - master
    paths:
      - 'plum/**'
      - .github/workflows/plum.yaml

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.PLUM }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          app_location: "plum" # App source code path relative to repository root
